env:
  server: "nginx/1.4.6 (Ubuntu)"
  realHost: localhost:8080

rules:
  - request:
      method: get
      url: /path?q={q}&p={p:.+}&k=1
    response:
      json:
        {
          a: "{{q}}",
          b: "{{p}}"
        }

  - request:
      method: _
      url: /seeOther
    response:
      seeOther: http://www.google.com

  - request:
      method: post
      url: /p2
    response:
      save: /photo

  - request:
      method: _
      url: _
    response:
      json:
        {
          default: true
        }