env:
  serverName: "nginx/1.4.6 (Ubuntu)"

constant:
  host1: localhost:8080
  dir1: /Users/richard/workspace/akqa/nikewomenswechat/src/main/webapp/static/dist

rule:
  - request:
      method: get
      url: /path?q={q}&p={p:.+}
    response:
      json:
        {
          a: "{{q}}",
          b: "{{p}}"
        }

  - request:
      method: _
      url: /seeOther
    response:
      seeOther: http://www.google.com

  - request:
      method: post
      url: /p2
    response:
      save: /photo

  - request:
      method: get
      url: /nw/{path:.+\.(?:html|jpg)}
    response:
#      file: "{{dir1}}/{{path}}"
      json:
        {
          path: "{{path}}"
        }
