env:
  serverName: "nginx/1.4.6 (Ubuntu)"

constant:
  host1: http://localhost:8080
  dir1: /Users/richard/workspace/akqa/nikewomenswechat/src/main/webapp/static/dist

rule:
  - request:
      method: get
      url: /path?q={q}&p={p:.+}
    response:
      json:
        {
          a: "{{q}}",
          b: "{{p}}"
        }

  - request:
      method: get
      url: /api/user/current
    response:
      call:
        url: "{{host1}}{{_}}"
        cookie: openid=oM_DGs0TB1synvlnRGzLfEqWU-Yk

  - request:
      method: get
      url: /nw/{path:.+\.(?:[a-z]+)}
    response:
      file: "{{dir1}}/{{path}}"

  - request:
      method: _
      url: /seeOther
    response:
      seeOther: http://www.google.com

  - request:
      method: get
      url: /nw/images/hub-text.2bd37f8b.png
    response:
      call: "{{host1}}{{_}}"

#  - request:
#      method: post
#      url: /p2
#    response:
#      save: /photo

#      json:
#        {
#          path: "{{path}}"
#        }
